aws_region="us-east-1"
aws_profile="LennoxT"
function_bucket_name="lambda-deepracer-bucket-ensono1024"
function_version="two"
s3_bucket_name_1="deepracer-ensono-bucket1"
s3_bucket_name_2="deepracer-ensono-bucket2"
